services:
  db:
    image: mysql:latest
    container_name: hospitals
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: hospital_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
